import { IsUUID, IsInt, IsOptional, IsEnum, IsBoolean } from "class-validator";

import { ScheduleStatus } from "@prisma/client";

export class CreateScheduleDto {
  @IsUUID()
  organizationId!: string;

  @IsUUID()
  departmentId!: string;

  @IsInt()
  month!: number;

  @IsInt()
  year!: number;

  @IsOptional()
  @IsEnum(ScheduleStatus)
  status?: ScheduleStatus;

  @IsOptional()
  @IsBoolean()
  autoGenerated?: boolean;
}
