export enum AlertSourceEngine {
    STAFFING_ENGINE = 'STAFFING_ENGINE',
    WORKLOAD_MONITOR = 'WORKLOAD_MONITOR',
    SCHEDULER_RULE_VALIDATOR = 'SCHEDULER_RULE_VALIDATOR',
    MANUAL_SUPERVISOR = 'MANUAL_SUPERVISOR',
}