export enum ConditionOperator {
  EQUALS = "EQUALS",

  NOT_EQUALS = "NOT_EQUALS",

  GREATER_THAN = "GREATER_THAN",

  LESS_THAN = "LESS_THAN",

  GREATER_OR_EQUALS = "GREATER_OR_EQUALS",

  LESS_OR_EQUALS = "LESS_OR_EQUALS",

  INCLUDES = "INCLUDES",

  NOT_INCLUDES = "NOT_INCLUDES",
}
