export enum ConditionType {
  TOTAL_HOURS = "TOTAL_HOURS",

  CONSECUTIVE_NIGHTS = "CONSECUTIVE_NIGHTS",

  REST_HOURS = "REST_HOURS",

  FATIGUE_SCORE = "FATIGUE_SCORE",

  NIGHT_SHIFTS = "NIGHT_SHIFTS",

  WEEKEND_SHIFTS = "WEEKEND_SHIFTS",

  MONTHLY_HOURS = "MONTHLY_HOURS",
}
