export enum WorkRuleActionEnum {
  BLOCK_ASSIGNMENT = "BLOCK_ASSIGNMENT",

  SEND_ALERT = "SEND_ALERT",

  NOTIFY_SUPERVISOR = "NOTIFY_SUPERVISOR",

  AUTO_REASSIGN = "AUTO_REASSIGN",

  CREATE_INCIDENT = "CREATE_INCIDENT",

  REMOVE_SHIFT = "REMOVE_SHIFT",

  REQUIRE_APPROVAL = "REQUIRE_APPROVAL",
}
