export enum ShiftChangeStatusEnum {
  AWAITING_OTHER_NURSE = "AWAITING_OTHER_NURSE",
  REJECTED_BY_NURSE = "REJECTED_BY_NURSE",
  ACCEPTED_BY_NURSE = "ACCEPTED_BY_NURSE",
  UNDER_SUPVERSION = "UNDER_SUPVERSION",
  APPROVED_BY_SUPERVISOR = "APPROVED_BY_SUPERVISOR",
  REJECTED_BY_SUPERVISOR = "REJECTED_BY_SUPERVISOR",
  REJECTED = "REJECTED",
  CANCELLED = "CANCELLED",
  EXPIRED = "EXPIRED",
  COMPLETED = "COMPLETED",
  ROLLED_BACK = "ROLLED_BACK",
  CONFLIC_DETECTED = "CONFLIC_DETECTED",
}
