export enum ShiftChangeDocumentTypeEnum {
  MEDICAL_CERTIFICATE = "MEDICAL_CERTIFICATE",

  EMERGENCY_JUSTIFICATION = "EMERGENCY_JUSTIFICATION",

  LEGAL_DOCUMENT = "LEGAL_DOCUMENT",

  INCIDENT_REPORT = "INCIDENT_REPORT",

  OTHER = "OTHER",
}
