import {
  Injectable,
  NotFoundException,
  BadRequestException,
} from "@nestjs/common";

import { PrismaService } from "@infra/database/prisma.service";

import { ScheduleStatus } from "@prisma/client";

@Injectable()
export class SchedulesService {
  constructor(private readonly prisma: PrismaService) {}

  /*
  |--------------------------------------------------------------------------
  | CREATE
  |--------------------------------------------------------------------------
  */

  async create(dto: any) {
    const exists = await this.prisma.schedule.findFirst({
      where: {
        departmentId: dto.departmentId,

        month: dto.month,

        year: dto.year,
      },
    });

    if (exists) {
      throw new BadRequestException("Schedule already exists for this period");
    }

    return this.prisma.schedule.create({
      data: dto,

      include: {
        department: true,
      },
    });
  }

  /*
  |--------------------------------------------------------------------------
  | FIND ALL
  |--------------------------------------------------------------------------
  */

  async findAll(query: any, user: any) {
    return this.prisma.schedule.findMany({
      where: {
        organizationId: user.organizationId,

        ...(query.departmentId && {
          departmentId: query.departmentId,
        }),

        ...(query.month && {
          month: query.month,
        }),

        ...(query.year && {
          year: query.year,
        }),

        ...(query.status && {
          status: query.status,
        }),
      },

      include: {
        department: true,

        scheduleEntries: true,
      },

      orderBy: {
        createdAt: "desc",
      },
    });
  }

  /*
  |--------------------------------------------------------------------------
  | FIND ONE
  |--------------------------------------------------------------------------
  */

  async findOne(id: string, user: any) {
    const schedule = await this.prisma.schedule.findFirst({
      where: {
        id,

        organizationId: user.organizationId,
      },

      include: {
        department: true,

        scheduleEntries: {
          include: {
            shift: true,
          },
        },

        scheduleVersions: true,

        optimizationRuns: true,
      },
    });

    if (!schedule) {
      throw new NotFoundException("Schedule not found");
    }

    return schedule;
  }

  /*
  |--------------------------------------------------------------------------
  | UPDATE
  |--------------------------------------------------------------------------
  */

  async update(id: string, dto: any, user: any) {
    await this.findOne(id, user);

    return this.prisma.schedule.update({
      where: {
        id,
      },

      data: dto,
    });
  }

  /*
  |--------------------------------------------------------------------------
  | DELETE
  |--------------------------------------------------------------------------
  */

  async remove(id: string, user: any) {
    await this.findOne(id, user);

    return this.prisma.schedule.delete({
      where: {
        id,
      },
    });
  }

  /*
  |--------------------------------------------------------------------------
  | PUBLISH
  |--------------------------------------------------------------------------
  */

  async publish(id: string, user: any) {
    await this.findOne(id, user);

    return this.prisma.schedule.update({
      where: {
        id,
      },

      data: {
        status: ScheduleStatus.PUBLISHED,

        publishedAt: new Date(),

        publishedById: user.sub,
      },
    });
  }

  /*
  |--------------------------------------------------------------------------
  | GENERATE
  |--------------------------------------------------------------------------
  */

  async generate(id: string, user: any) {
    const schedule = await this.findOne(id, user);

    if (schedule.status === ScheduleStatus.PUBLISHED) {
      throw new BadRequestException("Cannot regenerate published schedule");
    }

    return this.prisma.schedule.update({
      where: {
        id,
      },

      data: {
        status: ScheduleStatus.GENERATING,

        autoGenerated: true,
      },
    });
  }
}
