export enum NotificationTriggerEnum {
    SCHEDULE_PUBLISHED = "SCHEDULE_PUBLISHED",

    SHIFT_CHANGED = "SHIFT_CHANGED",

    SHIFT_APPROVED = "SHIFT_APPROVED",

    EMERGENCY_COVERAGE = "EMERGENCY_COVERAGE",

    LEAVE_APPROVED = "LEAVE_APPROVED",

    SYSTEM_ALERT = "SYSTEM_ALERT",
}